spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names:

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/helloboard?useUnicode=true&characterEncoding=utf8
#    username: fastcamp
#    password: fastcamp

logging:
  level:
      - ".=info"
      - "examples.boot=debug"
      - "org.springframework=info"